name: '3-Gateway'

on:
  workflow_dispatch:
    inputs:
      cluster:
        description: 'Current cluster to deploy'
        required: true
        default: 'my-gke-cluster'
  workflow_run:
    workflows: ["1-Cluster"]
    branches: [master]
    types:
      - completed

jobs:
  terraform:
    name: 'Gateway'
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

   # Get the GKE credentials so we can deploy to the cluster
    - uses: google-github-actions/get-gke-credentials@v0.2.1
      with:
        cluster_name: ${{github.event.inputs.cluster}}
        location: us-central1-a
        credentials: ${{ secrets.GKE_SA_KEY }}
    # The KUBECONFIG env var is automatically exported and picked up by kubectl.
    - id: apply-gateway
      run: kubectl apply -f 3_gateway/gateway.yml